export const defaultMale =
  "https://firebasestorage.googleapis.com/v0/b/dinnermate-8d37b.appspot.com/o/assets%2FFemale.png?alt=media&token=247bbd91-9ebf-4f5a-8911-b8d6b9c89e58";

export const defaultFemale =
  "https://firebasestorage.googleapis.com/v0/b/dinnermate-8d37b.appspot.com/o/assets%2FMale.png?alt=media&token=dfa379fe-607c-4ac5-8208-37f2745f5baa";

export const defaultUser = [
  {
    /* admin */
    user_birth: "20000101",
    user_email: "admin@example.com",
    user_name: "어드민",
    user_password: "motionbit0202!",
    user_profile: defaultFemale,
    user_type: "멘토",
  },
  {
    /* test */
    user_birth: "20000101",
    user_email: "test2@example.com",
    user_food: ["한식"],
    user_gender: "여",
    user_name: "테스트",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["서울특별시 강남구"],
    user_price: 8,
    user_profile: defaultFemale,
    user_type: "개인",
    user_info: "테스트 계정입니다.",
  },
  {
    /* dummy user1 */
    user_birth: "20000101",
    user_email: "user1@example.com",
    user_food: ["한식"],
    user_gender: "여",
    user_name: "박수정",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["서울특별시 강남구"],
    user_price: 8,
    user_profile: defaultFemale,
    user_type: "개인",
    user_info:
      "식사하고 카페에서 수다 떨 밥친구 매칭 원합니다! 키크고 운동 좋아하시는 분이 었으면 좋겠어요 평일 저녁 가능합니다 (:",
  },
  {
    /* dummy user2 */
    user_birth: "20000101",
    user_email: "user2@example.com",
    user_food: ["해산물 제외"],
    user_gender: "여",
    user_name: "이민지",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["부산 해운대구"],
    user_price: 2,
    user_profile: defaultFemale,
    user_type: "개인",
  },
  {
    /* dummy user3 */
    user_birth: "20000101",
    user_email: "user3@example.com",
    user_food: ["라멘"],
    user_gender: "남",
    user_name: "민준서",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["인천 남동구"],
    user_price: 6,
    user_profile: defaultMale,
    user_type: "개인",
    user_info:
      "남동구청 근처에서 오후 6시에서 9시 밥친구 매칭 원해요!\n남동구 근처 사시는 분이셨으면 좋겠어요 !!",
  },
  {
    /* dummy user4 */
    user_birth: "20000101",
    user_email: "user4@example.com",
    user_food: ["파스타"],
    user_gender: "여",
    user_name: "김민지",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["서울특별시 용산구"],
    user_price: 5,
    user_profile: defaultFemale,
    user_type: "개인",
    user_info:
      "우편집중국 근처가 직장이라 평일 12시에서 2시까지 점심시간 밥친구 가능합니다! 음식은 한식 좋아해요!! 채팅 주세요(:",
  },
  {
    /* dummy user5 */
    user_birth: "20000101",
    user_email: "user5@example.com",
    user_food: ["중식"],
    user_gender: "남",
    user_name: "유승민",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["서울특별시 양천구"],
    user_price: 8,
    user_profile: defaultMale,
    user_type: "개인",
  },
  {
    /* dummy user6 */
    user_birth: "20000101",
    user_email: "user6@example.com",
    user_food: ["다 잘먹어요!"],
    user_gender: "여",
    user_name: "김가현",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["서울특별시 서초구"],
    user_price: 2,
    user_profile: defaultFemale,
    user_type: "개인",
    user_info:
      "직장은 명촌이고 집은 중구라 울산 어디든 가능해요! 평일 저녁 시간에 밥친구 하실 분~~!!!",
  },
  {
    user_birth: "20000101",
    user_email: "user7@example.com",
    user_food: ["한식"],
    user_gender: "여",
    user_name: "김가현",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["서울특별시 서초구"],
    user_price: 10,
    user_profile: defaultFemale,
    user_type: "개인",
  },
  {
    user_birth: "20000101",
    user_email: "mento1@example.com",
    user_food: ["양식"],
    user_gender: "남",
    user_name: "김지훈",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["서울특별시 강남구"],
    user_price: 2,
    user_profile: defaultMale,
    user_category: "의류 쇼핑몰",
    user_type: "멘토",
    user_ingo:
      "의류 쇼핑몰 연 매출 20억 달성하고 디자이너 브랜드 런칭하여 운영중에 있어요. 의류 쇼핑몰로 매출 내고 있으신 분들만 식사권 신청 부탁드려요! 식사 가능 시간은 평일 저녁 7시~8시30분 가능합니다!",
  },
  {
    user_birth: "20000101",
    user_email: "mento2@example.com",
    user_food: ["한식"],
    user_gender: "여",
    user_name: "박서연",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["서울특별시 광진구"],
    user_price: 4,
    user_profile: defaultFemale,
    user_category: "해외구매대행",
    user_type: "멘토",
    user_info:
      "해외구매대행 처음 시작하시는 분들에게 방향성 및 소싱 방법에 대한 노하우 전수해드립니다. 유통업이 처음이시더라도 조언 들으신 후 사업하시는 것이 시간을 줄이실 수 있으실거에요. 해외구매대행으로만 작년 기준 매출 3억 달성하였고 올해는 아기 용품 브랜드 런칭하였습니다. 브랜드 런칭에도 도움드릴 수 있으니 관심있으신분들은 식사권 신청바랍니다. 식사가능 시간은 평일 저녁 6시 이후 부터 가능합니다",
  },
  {
    user_birth: "20000101",
    user_email: "mento3@example.com",
    user_food: ["한식"],
    user_gender: "여",
    user_name: "윤지영",
    user_password: "1q2w3e4r!",
    user_phone: "01012341234",
    user_place: ["서울특별시 서초구"],
    user_price: 10,
    user_profile: defaultFemale,
    user_category: "IT 및 소프트웨어 개발",
    user_type: "멘토",
    user_info:
      "에듀테크 it기업 엑싯경험으로 다양한 경험과 노하우를 알려드리겠습니다. 사업 조언 및 방향성 등에 도움이 많이 되실거에요 식사시간은 평일 점심시간만 역삼동에서 가능합니다. 12시~1시30분 입니다. 감사합니다. 식사 말고 커피 매칭으로 신청해주세요~ ",
  },
];
